// <auto-generated />
using System;
using Lowtab.Monster.Service.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lowtab.Monster.Service.Infrastructure.Migrations
{
    [DbContext(typeof(InternalDbContext))]
    [Migration("20251222113709_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArticleEntityTagEntity", b =>
                {
                    b.Property<Guid>("ArticleEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_entity_id");

                    b.Property<int>("TagsGroup")
                        .HasColumnType("integer")
                        .HasColumnName("tags_group");

                    b.Property<string>("TagsId")
                        .HasColumnType("text")
                        .HasColumnName("tags_id");

                    b.HasKey("ArticleEntityId", "TagsGroup", "TagsId")
                        .HasName("pk_article_entity_tag_entity");

                    b.HasIndex("TagsGroup", "TagsId")
                        .HasDatabaseName("ix_article_entity_tag_entity_tags_group_tags_id");

                    b.ToTable("article_entity_tag_entity", (string)null);
                });

            modelBuilder.Entity("Lowtab.Monster.Service.Domain.Entities.ArticleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PreviewImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("preview_image_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_articles");

                    b.ToTable("articles", (string)null);
                });

            modelBuilder.Entity("Lowtab.Monster.Service.Domain.Entities.TagEntity", b =>
                {
                    b.Property<int>("Group")
                        .HasColumnType("integer")
                        .HasColumnName("group");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Group", "Id")
                        .HasName("pk_tags");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("ArticleEntityTagEntity", b =>
                {
                    b.HasOne("Lowtab.Monster.Service.Domain.Entities.ArticleEntity", null)
                        .WithMany()
                        .HasForeignKey("ArticleEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_entity_tag_entity_articles_article_entity_id");

                    b.HasOne("Lowtab.Monster.Service.Domain.Entities.TagEntity", null)
                        .WithMany()
                        .HasForeignKey("TagsGroup", "TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_entity_tag_entity_tags_tags_group_tags_id");
                });
#pragma warning restore 612, 618
        }
    }
}
